//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCOMETAXBRACKET
    {
        public decimal ID { get; set; }
        public decimal BRACKETLEVEL { get; set; }
        public decimal RATE { get; set; }
        public Nullable<decimal> BMIN { get; set; }
        public Nullable<decimal> BMAX { get; set; }
    
        public virtual INCOMETAX INCOMETAX { get; set; }
    }
}
