//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCOMETAX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INCOMETAX()
        {
            this.INCOMETAXBRACKET = new HashSet<INCOMETAXBRACKET>();
        }
    
        public decimal ID { get; set; }
        public string TYPE { get; set; }
        public string FILINGTYPE { get; set; }
        public string FLAT { get; set; }
    
        public virtual STATE STATE { get; set; }
        public virtual TAXYEAR TAXYEAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCOMETAXBRACKET> INCOMETAXBRACKET { get; set; }
    }
}
