//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        public decimal PERSONID { get; set; }
        public string TYPE { get; set; }
        public string SUBSIDIZED { get; set; }
        public Nullable<decimal> MONTHLYRATE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
