//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalFinanceRestApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFContext : DbContext
    {
        public PFContext()
            : base("name=PFContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INCOMETAX> INCOMETAX { get; set; }
        public virtual DbSet<INCOMETAXBRACKET> INCOMETAXBRACKET { get; set; }
        public virtual DbSet<LOAN> LOAN { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<SAVINGS> SAVINGS { get; set; }
        public virtual DbSet<STATE> STATE { get; set; }
        public virtual DbSet<TAX> TAX { get; set; }
        public virtual DbSet<TAXYEAR> TAXYEAR { get; set; }
        public virtual DbSet<WAGE> WAGE { get; set; }
        public virtual DbSet<YEAR> YEAR { get; set; }
    }
}
